#!/usr/bin/bash

PACKAGES=(
    brave-bin
    criterion
    speed-test
)

modprobe vboxdrv

git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
cd ..
rm -rf paru-bin
paru -S --needed ${PACKAGES[@]}

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo -e "alias pls='sudo'\nalias -g G='|grep -i'" >> ~/.zshrc