#!/bin/bash

PACKAGES=(
    brave-bin
    shellcheck-bin
)

TECH_PACKAGES=(
    csfml
    criterion
    docker
    emacs
    gcovr
    gdb
    valgrind
)

BOLD="\033[1m"
NORMAL="\033[0m"

git clone https://aur.archlinux.org/paru-bin.git /tmp
cd /tmp/paru-bin || exit
makepkg -si --noconfirm

paru -Syyu --noconfirm --needed "${PACKAGES[@]}"
paru -S --needed "${TECH_PACKAGES[@]}"

# Oh My Zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo -e "alias pls='sudo'\nalias -g G='|grep -i'" >> ~/.zshrc

# Powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k

sed -i 's ZSH_THEME="robbyrussell" ZSH_THEME="powerlevel10k/powerlevel10k" g' ~/.zshrc

FONTS=(
    Regular
    Bold{,%20Italic}
    Italic
)

for FONT in "${FONTS[@]}"; do
    sudo wget --directory-prefix="/usr/share/fonts/TTF" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20"$FONT".ttf
done

echo -e "\n\n
    ${BOLD}DONE${NORMAL}
"
