#!/usr/bin/bash

USER0="ange"
MYHOSTNAME="${USER0^^}-DESKTOP"
SYS_CONFIG_DIR="config/system"

PACKAGES=(
    alacritty
    base-devel clang cmake python{,-pip}
    code
    discord
    gimp gwenview okular obs-studio
    git
    gparted ntfs-3g
    htop
    intel-ucode nvidia{,-settings}
    kdenlive
    linux-headers
    lutris steam wine-{gecko,mono,staging} winetricks
    man-{db,pages} texinfo
    neofetch
    networkmanager
    noto-fonts{,-{cjk,emoji}} ttf-dejavu
    openssh
    pipewire{,-{alsa,pulse}}
    tree
    unrar
    vim
    wget
    xclip
    xorg{,-xinit}
    zsh
)

sed -i "92s/.//; 93s/.//" /etc/pacman.conf
pacman -Syyu --noconfirm --needed "${PACKAGES[@]}"

ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
hwclock --systohc
timedatectl set-ntp true

sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g; s/#fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/g" /etc/locale.gen
locale-gen
echo "LANG=C" > /etc/locale.conf
echo "KEYMAP=fr-latin1" > /etc/vconsole.conf

echo "$MYHOSTNAME" > /etc/hostname
echo \
"127.0.0.1  localhost
::1         localhost
127.0.1.1   $MYHOSTNAME.localdomain $MYHOSTNAME" >> /etc/hosts

bootctl install

echo -e "\nroot passwd"
passwd

useradd -m -G wheel $USER0

echo "$USER0 passwd"
passwd $USER0

sed -i "s/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/" /etc/sudoers

cp -rf "$SYS_CONFIG_DIR"/xorg.conf.d/* /etc/X11/xorg.conf.d/
cp -rf "$SYS_CONFIG_DIR"/hooks /etc/pacman.d/
cp -rf "$SYS_CONFIG_DIR"/loader/* /boot/

systemctl enable NetworkManager
nvidia-xconfig
