#!/usr/bin/bash

USER0=ange

MYHOSTNAME=${USER0^^}-DESKTOP

ESP="/boot/efi"

PACKAGES=(
    alacritty
    base-devel clang cmake python{,-pip}
    code
    discord
    gimp gwenview okular obs-studio
    git
    gparted ntfs-3g
    grub efibootmgr os-prober
    htop
    intel-ucode nvidia{,-settings}
    linux-headers
    lutris steam wine-{gecko,mono,staging} winetricks
    man-{db,pages} texinfo
    nano
    neofetch
    networkmanager
    noto-fonts{,-{cjk,emoji}} ttf-dejavu
    openssh
    pipewire{,-{alsa,pulse}}
    tree
    unrar
    wget
    xclip
    xorg{,-xinit} xdotool
    zsh
)

sed -i "92s/.//; 93s/.//" /etc/pacman.conf
pacman -Syyu --noconfirm --needed ${PACKAGES[@]}

ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
hwclock --systohc
timedatectl set-ntp true

sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g; s/#fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/g" /etc/locale.gen
locale-gen
echo "LANG=C" > /etc/locale.conf
echo "KEYMAP=fr-latin1" > /etc/vconsole.conf

echo $MYHOSTNAME > /etc/hostname
echo \
"127.0.0.1	localhost
::1		localhost
127.0.1.1	$MYHOSTNAME.localdomain	$MYHOSTNAME" >> /etc/hosts

grub-install --target=x86_64-efi --efi-directory=$ESP --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

echo -e "\nroot passwd"
passwd

useradd -m -G wheel $USER0

echo "$USER0 passwd"
passwd $USER0

sed -i "s/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/" /etc/sudoers

echo \
'Section "InputClass"
	Identifier "keyboard"
	MatchIsKeyboard "on"
	Option "XkbLayout" "fr,us"
	Option "XkbVariant" "azerty,"
	Option "XkbOptions" "grp:alt_shift_toggle"
EndSection' > /etc/X11/xorg.conf.d/00-keyboard.conf

echo \
'Section "InputClass"
	Identifier "mouse"
	Driver "libinput"
	MatchIsPointer "yes"
	Option "AccelProfile" "flat"
EndSection' > /etc/X11/xorg.conf.d/50-mouse-acceleration.conf

systemctl enable NetworkManager
nvidia-xconfig

chown $USER0:$USER0 post_script
mv post_script /home/$USER0/
rm -r $(pwd)
